### ISSUE TITLE
Sign In Error

### ISSUE THREAD

**Issue by Sesa1988** [tnc1997/flutter-google-sign-in-desktop#1]
Hi,

I tried your package some days ago and it looked good. 
I got the consent screen and selected my google account but then when the redirect happenrf I got an error in my browser:

```
127.0.0.1 is currently unable to handle this request.
HTTP ERROR 500
```

I did it like this and followed your setup in the pubspec yaml.
Maybe something missing on the windows side to catch the redirect?

```
google_sign_in: ^6.2.1
google_sign_in_desktop: { git: https://github.com/tnc1997/flutter-google-sign-in-desktop.git }
google_sign_in_platform_interface: ^2.0.0
```

```
final String _appDataScope = "https://www.googleapis.com/auth/drive.appdata";
final String _fileScope = "https://www.googleapis.com/auth/drive.file";
final List<String> _defaultScopes = ['email', 'profile', 'openid'];

var signIn= GoogleSignIn(
        scopes: [_appDataScope, _fileScope, ..._defaultScopes],
        clientId: 'xxx',
        signInOption: SignInOption.standard,
      );

final GoogleSignInAccount? googleSignInAccount = await signIn.signIn();
```

**Comment by tnc1997** [comment]
Hi @Sesa1988, thank you for trying out this package! Have you completed step 2 and step 4 in the readme, to create a token store implementation and set the client secret?

**Comment by Sesa1988** [comment]
> Hi @Sesa1988, thank you for trying out this package! Have you completed step 2 and step 4 in the readme, to create a token store implementation and set the client secret?

Hi @tnc1997, thanks for the quick reply! 

I skipped this step because I had my own implementation for android and used that.
Can this be the issue? It does not look like it because it seems like the callback from the browser to the app did not work.

I can test it with your complete example but this would need more changes to my whole flow.
I also think I did not assign a secret probably because it was not needed for android.

**Comment by tnc1997** [comment]
> Can this be the issue?

Whilst a token data store implementation is not required, it is strongly recommended, otherwise the user will have to reauthenticate each time they start the application.

Registering a desktop client and setting the client secret is required because Google Sign In requires a client secret when exchanging the code for an access token.

**Comment by Sesa1988** [comment]
> > Can this be the issue?
> 
> Whilst a token data store implementation is not required, it is strongly recommended, otherwise the user will have to reauthenticate each time they start the application.
> 
> Registering a desktop client and setting the client secret is required because Google Sign In requires a client secret when exchanging the code for an access token.

I will test your implementation for the desktop version then, thanks!

**Comment by tnc1997** [comment]
No problem, you're welcome, if you experience any issues then feel free to reopen this.

**Comment by Sesa1988** [comment]
> No problem, you're welcome, if you experience any issues then feel free to reopen this.

It worked flawlessly. 

I just wrote another service for the desktop client without my own storage impelementation like you suggested.
