### ISSUE TITLE
Support custom redirect URI

### ISSUE THREAD

**Issue by davidmartos96** [tnc1997/flutter-google-sign-in-desktop#4]
**Is your feature request related to a problem? Please describe.**
Instead of relying on a local server waiting for the authorization code, an app might want to handle the adquisition of this code in a different way:
* Custom HTML rendered by the backend
* Custom URI scheme in the app

**Describe the solution you'd like**
I'm thinking on providing a `RedirectHandler` interface that can customize how the authorization code + state is obtained and provides it to the library so that it continues the auth flow.
The current implementation with the localhost server could be adapted to this interface as a default behavior.

```dart
instance.redirectHandler = MyRedirectHandler(...)
```
```dart
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart';

abstract class RedirectHandler {
  /// Initialize the handler, this could involve spinning up a server to listen for the redirect
  Future<void> init();
  /// Dispose of any resources used by the handler
  Future<void> dispose();
  
  Uri getRedirectUri();

  /// Obtain the redirect data from Google
  Future<AuthorizationCodeResponse> waitForAuthorizationCode();

  /// Once we have an user, we might want to customize the HTML response
  Future<void> finishFlow(GoogleSignInUserData userData);

  /// If there is an error during the process, an HTTP response could also be customized
  Future<void> onError(Object error, StackTrace stackTrace);
}

class AuthorizationCodeResponse {
  final String? code;
  final String? state;
  final String? error;

  bool get isError => error != null;

  AuthorizationCodeResponse(String this.code, this.state) : error = null;

  AuthorizationCodeResponse.error(String this.error)
      : code = null,
        state = null;
}

```

**Comment by tnc1997** [comment]
I would like to continue having a local server as the only available implementation for the meantime as that is the approach that Google recommends for macOS, Linux, Windows.

> To receive the authorization code using this URL, your application must be listening on the local web server. That is possible on many, but not all, platforms. However, if your platform supports it, this is the recommended mechanism for obtaining the authorization code.

That being said I think that it would definitely be useful to be able to customise the HTML that gets rendered after the authorisation code has been successfully received by the application.

> When your app receives the authorization response, for best usability it should respond by displaying an HTML page that instructs the user to close the browser and return to your app.

**Comment by tnc1997** [comment]
> I would like to continue having a local server as the only available implementation for the meantime as that is the approach that Google recommends for macOS, Linux, Windows.
